spring:
  datasource:
    url: jdbc:mysql://db-java-study.ct7mce7umdlx.us-west-2.rds.amazonaws.com:3306/banana
    username: admin
    password: ppppaaaa
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
server:
  port: 38080
